mail.sender=novaalearnn@gmail.com
mail.password=ywsp bret jxcr kkji
mail.username=mehdilakhoua123@gmail.com
mail.appPassword=rvbg escp jmxn ioqj
mail.fromName=PIDEV Java
password.reset.baseUrl=http://127.0.0.1:8765/reset-password
password.reset.validityMinutes=30
gemini.apiKey=AIzaSyB915j4qBo2yXOKYnAghA5Z2tiY1gsVfjc
gemini.endpoint=https://generativelanguage.googleapis.com/v1beta/models
gemini.model=gemini-2.5-flash
